name: ci-cd
on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
    
       - name: Build & Push Docker image
         uses: mr-smithers-excellent/docker-build-push@v3
         with:
            image: amnkashyap/nova-api-docs-swagger                                        #amnkashyap/angularproject
            tag: latest                                    #projectcicd
            registry: docker.io
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}      
            password: ${{ secrets.DOCKER_PASSWORD }} 
  

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: akhileshns/heroku-deploy@v3.12.12 
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: "sarah-oo"
  #         heroku_email: "sarahchimao@gmail.com"
